name: Merge to Main

on:
  pull_request:
    types: [closed]

jobs:
  merge:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Merge to Main
        run: |
          git fetch origin
          git checkout main
          git merge --no-ff ${{ github.event.pull_request.head.ref }} -m "Merge pull request #${{ github.event.pull_request.number }}"

      - name: Push Changes
        run: |
          git push origin main
