name: Merge to Main

on:
  pull_request:
    types: [closed]

jobs:
  merge:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Merge to Main
        run: git fetch
      

      - name: merge Changes
        run: git merge 
